language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

addons:
  postgresql: "9.3"
  mysql: "5.6"

env:
  global:
    - DEFAULT=1
  matrix:
    - TESTDB=mysql
    - TESTDB=postgresql

matrix:
  fast_finish: true
  include:
    - php: 7.1

install:
  - composer self-update
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - cp tests/createdb.sh.${TESTDB} tests/createdb.sh
  - sh tests/createdb.sh
  - export TESTDB=${TESTDB}

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"

notifications:
  email: false
